name: Run Testing

on:
  push:
    branches:
      - main
    paths-ignore: [ '*.md' ]

  pull_request:
    branches:
      - main
    paths-ignore: [ '*.md' ]

jobs:
  linux_tests:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        php: [ '8.0', '8.1' ]

    name: PHP ${{ matrix.php }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, libxml, mbstring, zip, pdo, json, curl
          tools: composer:v2
          coverage: none

      - name: Install Dependencies
        run: |
          composer install --prefer-dist --no-interaction

      - name: Execute Tests
        run: vendor/bin/phpunit --verbose --colors=always
